mv details original_code
mv movies.html original_code
mv tvshows.html original_code
mv README.md original_code
mv DEPLOYMENT.md original_code
mv QUICK_START_GITHUB.md original_code
mv deploy-to-github.sh original_code
mv run-dev.sh original_code
mv test_movie.csv original_code
mv populate-show-urls.cjs original_code
mv supabase-setup.sql original_code
mv add-rating-column.js original_code
mv SUPABASE_SETUP.md original_code
mv fix-all-rows.js original_code
mv SETUP_INSTRUCTIONS.txt original_code
mv RATING_SYSTEM_SUMMARY.md original_code
mv QUICK_START.md original_code
mv fix-table-issues.js original_code
mv remove-old-rating-column.js original_code
mv RATING_ENHANCEMENTS.md original_code
mv TEST_RATING_ENHANCEMENTS.md original_code
mv list-services.ts original_code
mv list-services.js original_code
mv STREAMING_PROVIDERS_EXPANSION.md original_code
mv SERVICE_EXPANSION_COMPLETE.md original_code
mv YOUTUBE_INTEGRATION_OPTIONS.md original_code
mv YOUTUBE_URL_IMPLEMENTATION.md original_code
mv DETAIL_PAGES_REMOVED.md original_code
mv CSV_FORMAT_AND_TROUBLESHOOTING.md original_code
mv movies.csv original_code
mv tvshows.csv original_code
